# Generated by Django 4.2.25 on 2025-10-05 06:57

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home Page'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_content',
            field=wagtail.fields.RichTextField(default='At Infortex Solutions Limited, we are dedicated to providing exceptional logistics and cargo services throughout Kenya. With years of experience in the industry, we understand the unique challenges of transportation and delivery in East Africa.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_title',
            field=models.CharField(default='About Infortex Solutions', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='coverage_areas',
            field=models.IntegerField(default=47),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_button_text',
            field=models.CharField(default='Contact Us', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_subtitle',
            field=models.CharField(default='Contact us today for a free quote and discover how we can help streamline your logistics needs.', max_length=300),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_title',
            field=models.CharField(default='Ready to Get Started?', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='deliveries_completed',
            field=models.IntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_text',
            field=models.CharField(default='Get Quote', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_url',
            field=models.URLField(blank=True, default='#contact'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.CharField(default='Your trusted partner for reliable transportation and delivery solutions across Kenya and East Africa.', max_length=300),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(default='Professional Logistics & Cargo Services in Kenya', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='satisfied_clients',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_subtitle',
            field=models.CharField(default='Comprehensive logistics solutions tailored to your business needs', max_length=300),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_title',
            field=models.CharField(default='Our Services', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='years_experience',
            field=models.IntegerField(default=10),
        ),
    ]
